name: stackfood_multivendor
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: #^4.7.2
    git:
      url: https://github.com/luis901101/getx_fork.git
      ref: old-4.7.0
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  google_maps_flutter_web: ^0.5.14+3
  carousel_slider: ^5.1.1
  shimmer_animation: ^2.2.2
  image_picker: ^1.2.1
  universal_html: ^2.3.0
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.2
  http: ^1.6.0
  pointer_interceptor: ^0.10.1+2
  phone_numbers_parser: ^9.0.16
  country_code_picker: ^3.4.1
  cached_network_image: ^3.4.1
  google_sign_in: ^7.2.0
  google_sign_in_web: ^1.1.0
  sign_in_with_apple: ^7.0.1
  flutter_facebook_auth: ^7.1.2
  photo_view: ^0.15.0
  dotted_border: ^3.1.0
  share_plus: ^12.0.1
  custom_map_markers: ^0.0.2+1
  card_swiper: ^3.0.1
  expandable_bottom_sheet: ^1.1.1+1
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  just_the_tooltip: ^0.0.12
  animated_flip_counter: ^0.3.4
  marquee: ^2.3.0
  syncfusion_flutter_datepicker: ^31.2.12
#  firebase_crashlytics: ^4.0.4
  file_picker: ^10.3.6
  path: ^1.9.1
  http_parser: ^4.1.2
  flutter_svg: ^2.2.2
  custom_info_window: ^1.0.1
  flutter_widget_from_html_core: ^0.17.0
  smooth_page_indicator: ^1.2.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  location: ^8.0.1
  permission_handler: ^12.0.1
  firebase_auth: ^6.1.2
  get_thumbnail_video: ^0.7.3
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  speech_to_text: ^7.3.0
  lottie: ^3.3.2
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/map/
    - assets/json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900